# Generated by Django 3.2.6 on 2021-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerment_src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
